#!/bin/bash
#
# Cross-build genefercu (CUDA backend) for Windows x64 from Linux (MinGW) —
# AOT fatbin build, mirroring `dev/build.sh --cuda` (the shipping design):
# every arch's SASS embedded, NO NVRTC at build or runtime, driver-only.
#
# The fatbins are reused byte-for-byte from the Linux build's cache
# (build_dev/fatbins/*.fatbin — GPU SASS is host-OS-independent). Run
# `bash dev/build.sh --cuda` first if the cache is empty (fatbin generation
# needs nvcc + a GPU for dump_src, so it stays a Linux-side step).
#
# Windows-specific pieces (same recipe as the ap27 cross-build):
#   - embedding: COFF .incbin assembly (.rdata section) instead of ELF .rodata
#   - BOINC libs cross-built via BOINC's lib/Makefile.mingw (winlibs/, shim)
#   - static MinGW libgmp.a built from source (winlibs/gmp)
#   - nvcuda.dll import library generated with dlltool from the driver
#     symbols the objects actually use (no Windows CUDA toolkit needed)
#   - POSIX-thread MinGW flavor (std::thread); -static bundles everything
#
# Env overrides: CUDA, BOINC_DIR, MINGW
#
set -euo pipefail
cd "$(dirname "$0")/.."

CUDA="${CUDA:-/usr/local/cuda-12.9}"
BOINC_DIR="${BOINC_DIR:-/home/ian/builds/boinc}"
MINGW="${MINGW:-x86_64-w64-mingw32}"
CXX="$MINGW-g++-posix"
ROOT="$(pwd)"
W="$ROOT/winlibs"
FAT="$ROOT/build_dev/fatbins"
OUT="$ROOT/bin/genefercu.exe"

[ -n "$(ls "$FAT"/*.fatbin 2>/dev/null)" ] || { echo "no fatbins in $FAT - run: bash dev/build.sh --cuda"; exit 1; }
mkdir -p "$W" bin

# --- GMP (static, MinGW) ------------------------------------------------------
if [ ! -f "$W/gmp/lib/libgmp.a" ]; then
  echo "[gmp] building static MinGW libgmp"
  ( cd "$W" \
    && curl -sL -o gmp-6.3.0.tar.xz https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz \
    && tar xf gmp-6.3.0.tar.xz && cd gmp-6.3.0 \
    && ./configure --host=$MINGW --disable-shared --enable-static --prefix="$W/gmp" >cfg.log 2>&1 \
    && make -j"$(nproc)" >make.log 2>&1 && make install >inst.log 2>&1 )
fi

# --- BOINC libs (MinGW), same shim as the ap27 cross-build ---------------------
if [ ! -f "$W/libboinc.a" ] || [ ! -f "$W/libboinc_api.a" ]; then
  echo "[boinc] cross-building BOINC libs"
  mkdir -p "$W/shim"
  cat > "$W/shim/config.h" <<'EOF'
#ifndef BOINC_MINGW_CONFIG_H
#define BOINC_MINGW_CONFIG_H
#define HAVE_STRCASECMP 1
#define HAVE__STRICMP 1
#define HAVE_STRDUP 1
#endif
EOF
  printf '#include <stddef.h>\n#include <string.h>\n#include "%s/lib/str_replace.h"\n' "$BOINC_DIR" > "$W/shim/force.h"
  ( cd "$W" && MINGW="$MINGW" BOINC_SRC="$BOINC_DIR" \
      make -f "$BOINC_DIR/lib/Makefile.mingw" \
        INCS="-I$W/shim -I$BOINC_DIR -I$BOINC_DIR/db -I$BOINC_DIR/lib -I$BOINC_DIR/api -I$BOINC_DIR/zip -I$BOINC_DIR/win_build" \
        OPTFLAGS="-O3 -include $W/shim/force.h" \
        libboinc.a libboinc_api.a )
fi

# --- embed the (reused) fatbins: COFF .incbin --------------------------------
# src/cuda/fatbins.h (the extern decls + lookup table) is regenerated by
# dev/build.sh --cuda and is platform-neutral; only the .s differs (PE .rdata).
echo "[embed] $(ls "$FAT"/*.fatbin | wc -l) fatbins (COFF)"
SF="$W/fatbins_win.s"
printf '/* auto-generated by build_win_cuda.sh */\n\t.section .rdata\n' > "$SF"
for f in "$FAT"/*.fatbin; do
  b=$(basename "$f" .fatbin); t=${b#*_n}; n=${t%%_*}; t=${b#*_rns}; rns=${t%%_*}; is32=${b##*_is}
  s="gf_n${n}_rns${rns}_is${is32}"
  printf '\t.global %s\n\t.global %s_end\n\t.align 8\n%s:\n\t.incbin "%s"\n%s_end:\n' "$s" "$s" "$s" "$f" "$s" >> "$SF"
done
"$MINGW-gcc" -c "$SF" -o "$W/fatbins_win.o"

# --- compile -------------------------------------------------------------------
BINC="-I$W/shim -I$BOINC_DIR -I$BOINC_DIR/api -I$BOINC_DIR/lib -I$BOINC_DIR/win_build"
FLAGS="-std=c++17 -O3 -DGPU -DCUDA -DGENEFER_EMBED_FATBINS -DBOINC $BINC -I$CUDA/include -I$W/gmp/include"

echo "[cc] main.cpp + transform_cu.cpp (mingw, posix threads)"
$CXX $FLAGS -c src/main.cpp         -o "$W/maingcu_win.o"
$CXX $FLAGS -c src/transform_cu.cpp -o "$W/transform_cu_win.o"

# --- nvcuda.dll import library --------------------------------------------------
echo "[imports] nvcuda.dll"
"$MINGW-nm" -u "$W/maingcu_win.o" "$W/transform_cu_win.o" | grep -oE 'cu[A-Za-z_0-9]+' | grep -v '^cuda' | sort -u > "$W/nvcuda.syms"
if grep -q nvrtc "$W/nvcuda.syms"; then echo "!! nvrtc symbols leaked into an AOT build"; exit 1; fi
{ echo "LIBRARY nvcuda.dll"; echo "EXPORTS"; cat "$W/nvcuda.syms"; } > "$W/nvcuda.def"
"$MINGW-dlltool" -d "$W/nvcuda.def" -l "$W/libnvcuda.a"
echo "  $(wc -l < "$W/nvcuda.syms") driver symbols, 0 nvrtc"

# --- link -----------------------------------------------------------------------
echo "[ld] $OUT (large: ~400MB of embedded SASS)"
$CXX -static -O3 "$W/maingcu_win.o" "$W/transform_cu_win.o" "$W/fatbins_win.o" \
     "$W/gmp/lib/libgmp.a" "$W/libboinc_api.a" "$W/libboinc.a" "$W/libnvcuda.a" \
     -o "$OUT"
echo "built: $OUT ($(du -h "$OUT" | cut -f1)) - driver-only, no NVRTC, no extra DLLs"
